services:
  - type: web
    name: mi-ecommerce-service
    env: docker
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mi-ecommerce-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: SUPABASE_S3_ACCESS_KEY_ID
        sync: false
      - key: SUPABASE_S3_SECRET_ACCESS_KEY
        sync: false
      - key: SUPABASE_S3_BUCKET_NAME
        sync: false
      - key: SUPABASE_S3_ENDPOINT_URL
        sync: false
      - key: SUPABASE_S3_REGION_NAME
        value: "sa-east-1"

databases:
  - name: mi-ecommerce-db
    plan: free
