services:
  - type: web
    name: mi-ecommerce
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn configuracion_principal.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mi-ecommerce-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: "4"
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*" # Podés cambiarlo por tu dominio real después

databases:
  - name: mi-ecommerce-db
    plan: free
