services:
  - type: web
    name: mi-ecommerce-service
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn configuracion_principal.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mi-ecommerce-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"

databases:
  - name: mi-ecommerce-db
    plan: free
