services:
  - type: web
    name: mi-ecommerce-service
    env: docker
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mi-ecommerce-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: ALLOWED_HOSTS
        value: "mi-ecommerce-4d7c.onrender.com"
      - key: SUPABASE_S3_ACCESS_KEY_ID
        sync: false
      - key: SUPABASE_S3_SECRET_ACCESS_KEY
        sync: false
      - key: SUPABASE_S3_BUCKET_NAME
        value: "productos"
      - key: SUPABASE_S3_ENDPOINT_URL
        sync: false
      - key: SUPABASE_S3_REGION_NAME
        value: "us-west-2"
      - key: SUPABASE_PROJECT_REF
        value: "adrjdpdgcpcggnoxyegx"

databases:
  - name: mi-ecommerce-db
    plan: free
